### ISSUE TITLE
[rllib] Unintended effect for change in PettingZooEnv.reset functionality?

### ISSUE THREAD

**Issue by rallen10** [PettingZoo-Team/PettingZoo#267]
To give context, I am working on a centralized critic PPO trainer (derived from [central_critic_2.py](https://github.com/ray-project/ray/blob/ray-1.0.1.post1/rllib/examples/centralized_critic_2.py)) for PettingZoo environments (specifically multiwalker). I had a version of this code working two months ago but I'm now revamping to incorporate updates from both rllib and pettingzoo.

There has been a fundamental change to [`pettingzoo_env.PettingZooEnv.reset()`](https://github.com/ray-project/ray/blob/master/rllib/env/pettingzoo_env.py#L99) and it's not clear to me if the effect was intentional. If it was intentional, it's not clear how to now handle my use case.

Previously the `reset()` function returned a dictionary of observations, one for each agent. See here: https://github.com/ray-project/ray/blob/4445f32798d72e291eac7661657092b06d7b9326/rllib/env/pettingzoo_env.py#L134

With the most recent commit to rllib on Nov 9, `reset()` now seems to return a dictionary with only a single observation for the agent specified by `self.env.agent_selection`. See here: https://github.com/ray-project/ray/blob/1999266bbaa82eac33a06b0b0a66821f14d77936/rllib/env/pettingzoo_env.py#L101

Was this effect intentional? If so, can you give any insight how to handle cases where all agents' observations are required simultaneously (which is what functions that call `reset` such as [`_MultiAgentEnvToBaseEnv.poll()`](https://github.com/ray-project/ray/blob/8b4b4bf0a2ae0f1c08095f1d23a74698528c52e0/rllib/env/base_env.py#L386) seem to expect)

**Comment by weepingwillowben** [comment]
Yes, this effect was intentional to support training of sequential games like chess. For parameter sharing or independent learning, this strategy works fine. 

I guess in hindsight it makes sense that centralized critics would not work as well with this method. 

To support all observations and actions being computed at the same time we have the parallel interface, which can be created with

```
parallel_env = pistonball_v2.parallel_env()
```
or
```
from pettingzoo.utils.to_parallel import to_parallel
parallel_env = to_parallel(pistonball_v2.env())
```
And can be converted to an rllib environment with 
```
from ray.rllib.env import ParallelPettingZooEnv
rllib_env = ParallelPettingZooEnv(parallel_env)
```

Which should work as before.

**Comment by rallen10** [comment]
Thank you for the feedback. Using `multiwalker_v5.parallel_env()` moved me passed my initial error, but now I'm running into a new, closely related error. Essentially it looks like `agent_selection` is still called deep in a nest of `reset` functions but the parallel interface doesn't have an `agent_selection` attribute. Here is the traceback:

```
Traceback (most recent call last):
  File "src/pettingzoo_arcade/sisl/multiwalker_v5_runner.py", line 91, in <module>
    dummy_env = multiwalker_v5_env_creator(hierarchical_args_dict['common']['config']['env_config'])
  File "/home/ross/Projects/Merlin/pettingzoo_arcade/src/pettingzoo_arcade/sisl/multiwalker_v5_src.py", line 136, in multiwalker_v5_env_creator
    env = PettingZooEnv(env)
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/ray/rllib/env/pettingzoo_env.py", line 97, in __init__
    self.reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/ray/rllib/env/pettingzoo_env.py", line 100, in reset
    self.env.reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/supersuit/base_aec_wrapper.py", line 32, in reset
    super().reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/pettingzoo/utils/wrappers.py", line 298, in reset
    super().reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/pettingzoo/utils/wrappers.py", line 50, in reset
    self.env.reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/supersuit/base_aec_wrapper.py", line 32, in reset
    super().reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/pettingzoo/utils/wrappers.py", line 298, in reset
    super().reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/pettingzoo/utils/wrappers.py", line 52, in reset
    self.agent_selection = self.env.agent_selection
AttributeError: 'to_parallel' object has no attribute 'agent_selection'
```

**Comment by rallen10** [comment]
Here is a minimum working example to reproduce the error with a less complex traceback:

+ ray version: `1.2.0.dev0`
+ pettingzoo version: `1.4.2`

```
#!/usr/bin/env python3
from ray.rllib.env.pettingzoo_env import PettingZooEnv
from pettingzoo.sisl import multiwalker_v5

def multiwalker_v5_env_creator():
    env = multiwalker_v5.parallel_env()
    env = PettingZooEnv(env)

if __name__ == "__main__":
    dummy_env = multiwalker_v5_env_creator()
```

```
Traceback (most recent call last):
  File "tests/parallel_env.py", line 11, in <module>
    dummy_env = multiwalker_v5_env_creator()
  File "tests/parallel_env.py", line 7, in multiwalker_v5_env_creator
    env = PettingZooEnv(env)
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/ray/rllib/env/pettingzoo_env.py", line 97, in __init__
    self.reset()
  File "/home/ross/miniconda3/envs/pettingzoo_arcade/lib/python3.8/site-packages/ray/rllib/env/pettingzoo_env.py", line 102, in reset
    self.env.agent_selection: self.env.observe(
AttributeError: 'to_parallel' object has no attribute 'agent_selection'
```

**Comment by rallen10** [comment]
Oops! I might have missed a key point in your response: `from ray.rllib.env import ParallelPettingZooEnv`

**Comment by rallen10** [comment]
Thanks! It looks like this worked. For posterity and completeness, here is a corrected version of the example I posted above (which is almost identical to what @weepingwillowben had already posted)

```
#!/usr/bin/env python3
from ray.rllib.env.pettingzoo_env import ParallelPettingZooEnv
from pettingzoo.sisl import multiwalker_v5

def multiwalker_v5_env_creator():
    env = multiwalker_v5.parallel_env()
    env = ParallelPettingZooEnv(env)

if __name__ == "__main__":

    dummy_env = multiwalker_v5_env_creator()
```

**Comment by weepingwillowben** [comment]
Glad this worked.
