### ISSUE TITLE
Prison Crashing (our fault)

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/PettingZoo#304]
So I was using prison per this script: 

https://github.com/justinkterry/all_pistonball/tree/90f1dd19508c8ab01af5d858677c13ce42516170

And this happened:

```
justinkterry@prophet:~/all_pistonball$ python3 run.py
pygame 2.0.0 (SDL 2.0.12, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/justinkterry/.local/lib/python3.6/site-packages/all/core/state.py:82: UserWarning: ValueError while creating StateArray for key "agent", omitting.
  warnings.warn('ValueError while creating StateArray for key "{}", omitting.'.format(key))
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
[WARNING]: Received an action [nan] that was outside action space Box(-24.0, 24.0, (1,), float32). Environment is clipping to space
Traceback (most recent call last):
  File "run.py", line 100, in <module>
    experiment.train(1e6)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/all/experiments/multiagent_env_experiment.py", line 67, in train
    self._run_training_episode()
  File "/home/justinkterry/.local/lib/python3.6/site-packages/all/experiments/multiagent_env_experiment.py", line 122, in _run_training_episode
    self._env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/all/environments/multiagent_pettingzoo.py", line 59, in step
    self._env.step(self._convert(action))
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/supersuit/base_aec_wrapper.py", line 45, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 238, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 178, in step
    super().step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/utils/wrappers.py", line 63, in step
    self.env.step(action)
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/butterfly/prison/prison.py", line 340, in step
    self.draw()
  File "/home/justinkterry/.local/lib/python3.6/site-packages/pettingzoo/butterfly/prison/prison.py", line 269, in draw
    self.screen.blit(self.prisoners[p].get_sprite(), self.prisoners[p].position)
TypeError: argument 1 must be pygame.Surface, not None
```

**Comment by weepingwillowben** [comment]
So the problem here is that prison crashes in a weird way when it gets a nan action. Nan is outside the observation space, so we shouldn't really expect it to work anyways. I put in an error message in a wrapper and made a PR for it #306
