### ISSUE TITLE
Some errors appear when training DQN model in PettingZoo using stable-baselines3

### ISSUE THREAD

**Issue by ST-QI** [PettingZoo-Team/PettingZoo#467]
### 🐛 Bug

I want to train DQN reinforcement learning model in PettingZoo environment with the help of Stable-Baselines3.
However i encounter some errors when calling 'model.learn()'.

### To Reproduce

```python
from pettingzoo.magent import battle_v3
import supersuit as ss
from stable_baselines3 import DQN
from stable_baselines3.dqn import MlpPolicy

env = battle_v3.parallel_env()
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 1, base_class='stable_baselines3')
model = DQN(MlpPolicy, env)
model.learn(total_timesteps=1000)
```

```bash
Traceback (most recent call last):
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b6d315bf50c1>", line 1, in <module>
    runfile('/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py', wdir='/home/stq/RL/pytorch_DGN/Pettingzoo')
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py", line 9, in <module>
    model = DQN(MlpPolicy, env)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/dqn/dqn.py", line 90, in __init__
    super(DQN, self).__init__(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 109, in __init__
    super(OffPolicyAlgorithm, self).__init__(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 174, in __init__
    raise ValueError(
ValueError: Error: the model does not support multiple envs; it requires a single vectorized environment.
```

If i annotate the following sentence:

```python
from pettingzoo.magent import battle_v3
import supersuit as ss
from stable_baselines3 import DQN
from stable_baselines3.dqn import MlpPolicy

env = battle_v3.parallel_env()
env = ss.pettingzoo_env_to_vec_env_v0(env)
#env = ss.concat_vec_envs_v0(env, 1, base_class='stable_baselines3')
model = DQN(MlpPolicy, env)
model.learn(total_timesteps=1000)
```

I get the error as follows:

```bash
Traceback (most recent call last):
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b6d315bf50c1>", line 1, in <module>
    runfile('/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py', wdir='/home/stq/RL/pytorch_DGN/Pettingzoo')
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py", line 10, in <module>
    model.learn(total_timesteps=1000)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/dqn/dqn.py", line 239, in learn
    return super(DQN, self).learn(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 338, in learn
    total_timesteps, callback = self._setup_learn(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 314, in _setup_learn
    return super()._setup_learn(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 420, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (162,13,13,5) into shape (13,13,5)
```

If i annotate the following sentence:

```python
from pettingzoo.magent import battle_v3
import supersuit as ss
from stable_baselines3 import DQN
from stable_baselines3.dqn import MlpPolicy

env = battle_v3.parallel_env()
#env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 1, base_class='stable_baselines3')
model = DQN(MlpPolicy, env)
model.learn(total_timesteps=1000)
```

I get the error as follows:

```bash
Traceback (most recent call last):
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b6d315bf50c1>", line 1, in <module>
    runfile('/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py', wdir='/home/stq/RL/pytorch_DGN/Pettingzoo')
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py", line 8, in <module>
    env = ss.concat_vec_envs_v0(env, 1, base_class='stable_baselines3')
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/supersuit/vector/vector_constructors.py", line 49, in concat_vec_envs_v0
    vec_env = MakeCPUAsyncConstructor(num_cpus)(*vec_env_args(vec_env, num_vec_envs))
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/supersuit/vector/vector_constructors.py", line 14, in vec_env_args
    return [env_fn] * num_envs, env.observation_space, env.action_space
AttributeError: '_parallel_env' object has no attribute 'observation_space'
```

If i annotate the following sentences:

```python
from pettingzoo.magent import battle_v3
import supersuit as ss
from stable_baselines3 import DQN
from stable_baselines3.dqn import MlpPolicy

env = battle_v3.parallel_env()
#env = ss.pettingzoo_env_to_vec_env_v0(env)
#env = ss.concat_vec_envs_v0(env, 1, base_class='stable_baselines3')
model = DQN(MlpPolicy, env)
model.learn(total_timesteps=1000)
```

I get the error as follows:

```bash
Traceback (most recent call last):
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b6d315bf50c1>", line 1, in <module>
    runfile('/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py', wdir='/home/stq/RL/pytorch_DGN/Pettingzoo')
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/stq/pycharm-2021.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/stq/RL/pytorch_DGN/Pettingzoo/debug.py", line 9, in <module>
    model = DQN(MlpPolicy, env)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/dqn/dqn.py", line 90, in __init__
    super(DQN, self).__init__(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 109, in __init__
    super(OffPolicyAlgorithm, self).__init__(
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 160, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 197, in _wrap_env
    env = Monitor(env)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 39, in __init__
    super(Monitor, self).__init__(env=env)
  File "/home/stq/anaconda3/envs/pytorch/lib/python3.8/site-packages/gym/core.py", line 215, in __init__
    self.action_space = self.env.action_space
AttributeError: '_parallel_env' object has no attribute 'action_space'
```

### Expected behavior

I want to train DQN model in PettingZoo environment by using Stable-Baselines3 successfully.

**Comment by benblack769** [comment]
I apologize for the late response here.

So unfortunately using DQN with SB3 is just not possible. The reason is that PettingZoo's support for SB3 depends on turning the multiagent environment into a vector environment (your first code example). 

SB3 simply does not support using a vector environment for DQN, though it does support PPO and A2C. Please follow up on this issue in SB3: https://github.com/DLR-RM/stable-baselines3/issues/179 which relates to supporting vector environments in DQN and SAC.
