### ISSUE TITLE
Error when running tutorial 13 lines

### ISSUE THREAD

**Issue by bogdanvaduva9** [PettingZoo-Team/PettingZoo#476]
When running the tutorial from [here](https://github.com/PettingZoo-Team/PettingZoo/blob/master/tutorials/13_lines.py)
I get the following error: 

`Traceback (most recent call last):
  File "G:/Projects/furry-disco/prj.py", line 13, in <module>
    env = ss.concat_vec_envs_v0(env, 8, num_cpus=2, base_class='stable_baselines3')
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\vector_constructors.py", line 49, in concat_vec_envs_v0
    vec_env = MakeCPUAsyncConstructor(num_cpus)(*vec_env_args(vec_env, num_vec_envs))
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\constructors.py", line 38, in constructor
    return ProcConcatVec(cat_env_fns, obs_space, act_space, num_fns * envs_per_env, example_env.metadata)
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\multiproc_vec.py", line 99, in __init__
    env_nums = self._receive_info()
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\multiproc_vec.py", line 127, in _receive_info
    data = cin.recv()
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\utils\shared_array.py", line 20, in __setstate__
    self._set_np_arr()
  File "C:\Users\mihaita.vaduva\Miniconda3\lib\site-packages\supersuit\vector\utils\shared_array.py", line 13, in _set_np_arr
    self.np_arr = np.frombuffer(self.shared_arr, dtype=self.dtype).reshape(self.shape)
AttributeError: 'SharedArray' object has no attribute 'dtype'`

**Comment by benblack769** [comment]
Unfortunately, pettingzoo does not have full support for windows. Supporting windows for this sort of software (involving graphics, physics simulation, etc) is uncommon because it is just too hard. In the long run, I recommend installing the windows subsystem for linux, i.e. ubuntu for windows, and running the code in that subsystem instead. I have had significant success with using it personally. In the short run though, I would try turning off multiprocessing in the example, and see if that works.

```
env = ss.concat_vec_envs_v0(env, 8, num_cpus=1, base_class='stable_baselines3')
```

**Comment by jkterry1** [comment]
The PettingZoo (and Gym) readme's both have this line: "We support Python 3.6, 3.7, 3.8 and 3.9 on Linux and macOS. We will accept PRs related to Windows, but do not officially support it."
